site_name: PVE Documentation
site_description: PVE 文档
site_url: https://skn-33.github.io/pve-doc/

repo_name: skn-33/pve-doc
repo_url: https://github.com/skn-33/pve-doc

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md

plugins:
  - search
