site_name: butubb的pve
site_description: PVE 配置文档
site_url: https://pve.doc.butubb.cn

repo_name: 8butubb/pve_doc
repo_url: https://github.com/8butubb/pve_doc

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - PVE宿主机:
    - 铭凡N5 Air: pve-host/index.md

plugins:
  - search
  - git-revision-date-localized

copyright: "COPYRIGHT_PLACEHOLDER"
