name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install mkdocs-material mkdocs-git-revision-date-localized-plugin
      - name: Set build info
        run: |
          BUILD_YEAR=$(date -u +'%Y')
          BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S')
          BUILD_COMMIT=${GITHUB_SHA::8}
          sed -i "s/COPYRIGHT_PLACEHOLDER/\&copy; ${BUILD_YEAR} butubb \&nbsp;\| \&nbsp; 构建时间: ${BUILD_DATE} \&nbsp;\| \&nbsp; Commit: ${BUILD_COMMIT}/" mkdocs.yml
      - run: mkdocs build
      - id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - id: deploy
        uses: actions/deploy-pages@v4
